### ISSUE TITLE
gulp watch: failed

### ISSUE THREAD

**Issue by wachyudisonang** [SKempin/reactjs-tmdb-app#10]
I've got these when running command: gulp watch

> #
> # Fatal error in ../deps/v8/src/api.cc, line 1248
> # Check failed: !value_obj->IsJSReceiver() || value_obj->IsTemplateInfo().
> #
> Illegal instruction: 4

i got it fixed after ran these to get updates from packages:

```
npm i -g npm-check-updates
npm-check-updates -u
npm install
gulp watch
```

And now got another issue: 

> [12:22:17] Starting 'html'...
> **[12:22:17] 'html' errored after 33 ms**
> **[12:22:17] TypeError: $.useref.assets is not a function**

**Comment by wachyudisonang** [comment]
i got it fixed after ran these to get updates from packages:

```
npm i -g npm-check-updates
npm-check-updates -u
npm install
```

And now got another issue: 

> [12:22:17] Using gulpfile /Applications/XAMPP/xamppfiles/htdocs/react/reactjs-tmdb-app/gulpfile.js
> [12:22:17] Starting 'sync group3:0'...
> [12:22:17] Starting 'sync group0:0'...
> [12:22:17] Starting 'clean'...
> [12:22:17] Finished 'clean' after 6.81 ms
> [12:22:17] Finished 'sync group0:0' after 7.57 ms
> [12:22:17] Starting 'sync group0:1'...
> [12:22:17] Starting 'html'...
> **[12:22:17] 'html' errored after 33 ms**
> **[12:22:17] TypeError: $.useref.assets is not a function**
>     at Gulp.<anonymous> (/Applications/XAMPP/xamppfiles/htdocs/react/reactjs-tmdb-app/gulpfile.js:51:27)
>     at module.exports (/Applications/XAMPP/xamppfiles/htdocs/react/reactjs-tmdb-app/node_modules/orchestrator/lib/runTask.js:34:7)
>     at Gulp.Orchestrator._runTask (/Applications/XAMPP/xamppfiles/htdocs/react/reactjs-tmdb-app/node_modules/orchestrator/index.js:273:3)
>     at Gulp.Orchestrator._runStep (/Applications/XAMPP/xamppfiles/htdocs/react/reactjs-tmdb-app/node_modules/orchestrator/index.js:214:10)
>     at Gulp.Orchestrator.start (/Applications/XAMPP/xamppfiles/htdocs/react/reactjs-tmdb-app/node_modules/orchestrator/index.js:134:8)
>     at Gulp.<anonymous> (/Applications/XAMPP/xamppfiles/htdocs/react/reactjs-tmdb-app/node_modules/gulp-sync/lib/index.js:51:27)
>     at module.exports (/Applications/XAMPP/xamppfiles/htdocs/react/reactjs-tmdb-app/node_modules/orchestrator/lib/runTask.js:34:7)
>     at Gulp.Orchestrator._runTask (/Applications/XAMPP/xamppfiles/htdocs/react/reactjs-tmdb-app/node_modules/orchestrator/index.js:273:3)
>     at Gulp.Orchestrator._runStep (/Applications/XAMPP/xamppfiles/htdocs/react/reactjs-tmdb-app/node_modules/orchestrator/index.js:214:10)
>     at /Applications/XAMPP/xamppfiles/htdocs/react/reactjs-tmdb-app/node_modules/orchestrator/index.js:279:18

**Comment by wachyudisonang** [comment]
# *Fixed - all run smoothly now

I know that above issue appears after I do updates the packages, so some adjustments needed are:

1. update gulpfile.js as mentioned on https://www.npmjs.com/package/gulp-useref
2. install babel to recognize .js as .jsx
```
npm install --save-dev babel-preset-es2015
npm install --save-dev babel-preset-react
```
3. create .babelrc to project root as follow:
```
{
  "presets": ["es2015", "react"]
}
```

**Comment by zhangenming** [comment]
@wachyudisonang 
After I finished following these steps still have problems

<img width="1026" alt="screenshot" src="https://user-images.githubusercontent.com/21235555/34806204-9b14883a-f6bc-11e7-94a8-30c14522cdb4.png">
Error: File not found with singular glob: /Users/kaixunkejigcs/Desktop/fox/reactjs-tmdb-app/bower_components/jquery/dist/jquery.js (if this was purposeful, use `allowEmpty` option)
    
at DestroyableTransform.<anonymous> (/Users/kaixunkejigcs/Desktop/fox/reactjs-tmdb-app/node_modules/_gulp-useref@3.1.4@gulp-useref/index.js:65:32)

**Comment by zhangenming** [comment]
solved....
You forgot this step
`bower install`
